name: Build Docker image
on:
  push:
jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile